// import localFont from "next/font/local";
'use client'
import "./globals.css";
import { Provider } from "react-redux";
// import store from "@/store/store";
import { store } from "@/store";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-manrope antialiased text-gray-900 min-h-screen overflow-x-hidden"
        suppressHydrationWarning
      >
        <Provider store={store}>
          {children}

        </Provider>

      </body>
    </html>
  );
}
